Garage3.0.Web/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage3._0.Core;
using Garage3._0.Data;
using Garage3._0.Web.Models;
using Garage3._0.Web.Models.Entities;




namespace Garage3._0.Web.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly GarageContext _context;
        public int nummer;
        public PersonInSession ps = new PersonInSession();

        public VehiclesController(GarageContext context)
        {
            _context = context;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index()
        {
            var garageContext = _context.Vehicle.Include(v => v.VehicleType);
            return View(await garageContext.ToListAsync());
        }

        public IActionResult SearchMemberById(int memberId)
        {
            TempData["Member"] = memberId.ToString();
            return View("Create");
        }

       
        public IActionResult SearchMemberInVehicleTable(string id)
        {
            
            if (_context.Vehicle?.FirstOrDefault(v => v.Id== Int32.Parse(id)) == null)
            {
                TempData["Message"] = "You do not have any registered Vehicle.";
                return View("Create");
            }
            else if (_context.Vehicle?.FirstOrDefault(v => v.Id == Int32.Parse(id)) != null)
            {
                
                //var membership = await _context.Membership.FindAsync(ms.Id);
               var vehicle = _context.Vehicle
                    .Where(v => v.Id == Int32.Parse(id))
                .ToList();    
                return View("RegisteredVehicles",vehicle);
            }
        
            return View("RegisteredVehicles");
        }

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vehicle == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .Include(v => v.VehicleType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Create
        public IActionResult Create(int id)
        {
            Vehicle myVehicle = new Vehicle();
            myVehicle.Fuel = "";
            //myVehicle.VehicleTypeId =1;
            myVehicle.Wheels = 2;
            myVehicle.Brand = "";
            myVehicle.RegistrationNumber = "";
            myVehicle.Color = "";
            myVehicle.MembershipId= id;
            ViewData["VehicleTypeId"] = new SelectList(_context.Set<VehicleType>(), "Id","Name");
            return View("Create",myVehicle);
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("VehicleTypeId,Fuel,Wheels,Brand,RegistrationNumber,Color,MembershipId")] Vehicle vehicle)
        public async Task<IActionResult> Create(int VehicleTypeId, string Fuel, int Wheels, string Brand,string RegistrationNumber, string Color, int MembershipId)
        {
            /*if (ModelState.IsValid)
            {
                if (_context.Vehicle?.FirstOrDefault(v => v.RegistrationNumber == vehicle.RegistrationNumber) != null)
                {
                    TempData["Message"] = "Licens exist";
                    ViewBag.LicenseNumberExists = true;
                    return View("Index");
                }
                else if (_context.Vehicle?.FirstOrDefault(v => v.RegistrationNumber == vehicle.RegistrationNumber) == null)
                {*/
            //var obj = TempData["PersonId"];
              



            Vehicle myVehicle=new Vehicle();
            myVehicle.Fuel = Fuel;
            myVehicle.VehicleTypeId = VehicleTypeId;
            myVehicle.Wheels = Wheels;
            myVehicle.Brand=Brand;
            myVehicle.RegistrationNumber = RegistrationNumber;
            myVehicle.Color = Color;
            myVehicle.MembershipId=MembershipId;
            TempData["Message"] = "Vehicle added";
            _context.Add(myVehicle);
                 await _context.SaveChangesAsync();
            // }
            //}
            //Select all
            var vehic = from e in _context.Vehicle select e;
            //ViewData["VehicleTypeId"] = new SelectList(_context.Set<VehicleType>(), "Name", "Id", myVehicle.VehicleTypeId);
            return View("Index",vehic);
        }

        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vehicle == null)
            {
                return View("RegisteredVehicles");
                //return NotFound();
            }

            var vehicle = await _context.Vehicle.FindAsync(id);
            if (vehicle == null)
            {
                return NotFound();
            }
            ViewData["VehicleTypeId"] = new SelectList(_context.Set<VehicleType>(), "Id", "Id", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MembershipId,VehicleTypeId,Fuel,Wheels,Brand,RegistrationNumber,Colour")] Vehicle vehicle)
        {
            if (id != vehicle.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["VehicleTypeId"] = new SelectList(_context.Set<VehicleType>(), "Id", "Id", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vehicle == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .Include(v => v.VehicleType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Parking vm = new Parking();
            if (_context.Vehicle == null)
            {
                return Problem("Entity set 'GarageContext.Vehicle'  is null.");
            }
            var vehicle = await _context.Vehicle.FindAsync(id);
            if (vehicle != null)
            {
                _context.Vehicle.Remove(vehicle);
            }
            
            await _context.SaveChangesAsync();
            return View("Receipt",vm);
            //return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
          return (_context.Vehicle?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Garage3.0.Web/Views/Vehicles/Create.cshtml
@using System.Collections
@model Garage3._0.Core.Vehicle

@{
    ViewData["Title"] = "Create";
}

<h1>Create Vehicle</h1>


@if (TempData["Message"] != null)
{
<div class="row pt-4">
        <div class="col-12">
	       <div class="alert alert-primary text-center">
	          <strong>@TempData["Message"]</strong>
	       </div>
        </div>
    </div>
}

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Vehicles" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
          @* <div class="form-group">
                <label asp-for="VehicleTypeId" class="control-label"></label>
                <select asp-for="VehicleTypeId" class="form-control" />
                <span asp-validation-for="VehicleTypeId" class="text-danger"></span>
            </div>*@
            
            <div>
                
               @Html.DropDownList("VehicleTypeId")
                
                                                                   
            </div>
          
             <div class="form-group">
                <label asp-for="Fuel" class="control-label"></label>
                <input asp-for="Fuel" class="form-control" />
                <span asp-validation-for="Fuel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wheels" class="control-label"></label>
                <input asp-for="Wheels" class="form-control" />
                <span asp-validation-for="Wheels" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="text" asp-for="MembershipId" />
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage3.0.Web/Views/Vehicles/Delete.cshtml
@model Garage3._0.Core.Vehicle

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fuel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fuel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Wheels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Wheels)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehicleType.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Garage3.0.Web/Views/Vehicles/Details.cshtml
@model Garage3._0.Core.Vehicle

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fuel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fuel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Wheels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Wheels)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehicleType.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Garage3.0.Web/Views/Vehicles/Edit.cshtml
@model Garage3._0.Core.Vehicle

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="MembershipId" class="control-label"></label>
                <select asp-for="MembershipId" class="form-control" asp-items="ViewBag.MembershipId"></select>
                <span asp-validation-for="MembershipId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VehicleTypeId" class="control-label"></label>
                <select asp-for="VehicleTypeId" class="form-control" asp-items="ViewBag.VehicleTypeId"></select>
                <span asp-validation-for="VehicleTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fuel" class="control-label"></label>
                <input asp-for="Fuel" class="form-control" />
                <span asp-validation-for="Fuel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wheels" class="control-label"></label>
                <input asp-for="Wheels" class="form-control" />
                <span asp-validation-for="Wheels" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage3.0.Web/Views/Vehicles/Index.cshtml
@model IEnumerable<Garage3._0.Core.Vehicle>

@{
    ViewData["Title"] = "Index";
}

<div class="container ">
    <div class="row p-4">
        <div class="col-12">
           <div class="display-6 text-center">
              Registered vehicles
           </div>
         </div>
    </div>

    
@if (TempData["Message"] != null)
    {
        <div class="row pt-4">
            <div class="col-12">
                <div class="alert alert-primary text-center">
                    <strong>@TempData["Message"]</strong>
                </div>
            </div>
        </div>
    }


<table class="table pt-4">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            <th>
                @Html.DisplayNameFor(model => model.MembershipId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fuel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Wheels)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegistrationNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehicleType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MembershipId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fuel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wheels)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleType.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>

Garage3.0.Web/Views/Vehicles/Receipt.cshtml
@model Garage3._0.Core.Parking

@{
    ViewData["Title"] = "Unpark";
}
 
@{
    DateTime arrivalTime = Model.ArrivalTime;
    int pricePerHour = 10;
    int totMinutes = 0;
    int totPrice = 0;
    TimeSpan mindate = DateTime.Now.Subtract(arrivalTime);
    int parkHours=mindate.Hours;
    int parkMinutes = mindate.Minutes;
    if(mindate.Days == 0)
    {
        totMinutes=mindate.Hours * 60 + mindate.Minutes;
        totPrice=mindate.Hours * 60 + mindate.Minutes;
    }
    else if(mindate.Days > 0)
    {
        totMinutes=mindate.Hours * 60 + mindate.Minutes;
        totPrice=mindate.Days*100+totMinutes*10/60;
    }
    
    

}

<div class="container p-5 bg-primary text-white">
    
  <div class="header"><H3>Receipt</H3>
    <div class="row text-center">
       <div class="col-12  p-5">
           <h3>Parked Vehicle: @Html.DisplayFor(model => model.VehicleId)<br />Time of Arrival: @Html.DisplayFor(model => model.ArrivalTime)</h3>
       </div>
    </div>
    <div class="border border-1">  
       <div class="row">
           <div class="col-4  p-5"><h3>Days: @mindate.Days</h3></div>
           <div class="col-4  p-5"><h3>Hours: @parkHours</h3></div>
           <div class="col-4 text-start p-5"><h3>Minutes: @parkMinutes</h3></div>
       </div>
       <div class="row">
            <div class="col-12  text-center p-5"><H3>Price: @totPrice Kr</H3></div>
       </div>   
       
    </div>
  </div>
</div>

Garage3.0.Web/Views/Vehicles/RegisteredVehicles.cshtml
@model IEnumerable<Garage3._0.Core.Vehicle>
@{
    ViewData["Title"] = "Vehicles";
}
<h1>Registered Vehicles</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MembershipId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fuel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Wheels)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegistrationNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehicleType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
             <th>
                @Html.DisplayNameFor(modelItem => item.MembershipId)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.Fuel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wheels)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleType.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>